/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CircuitoRouteImport } from './routes/circuito'
import { Route as CopilotoRouteImport } from './routes/copiloto'
import { Route as FotossinteseRouteImport } from './routes/fotossintese'
import { Route as MinigamesRouteImport } from './routes/minigames'
import { Route as QuimicaRouteImport } from './routes/quimica'
import { Route as QuizRouteImport } from './routes/quiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitoRoute = CircuitoRouteImport.update({
  id: '/circuito',
  path: '/circuito',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotoRoute = CopilotoRouteImport.update({
  id: '/copiloto',
  path: '/copiloto',
  getParentRoute: () => rootRouteImport,
} as any)
const FotossinteseRoute = FotossinteseRouteImport.update({
  id: '/fotossintese',
  path: '/fotossintese',
  getParentRoute: () => rootRouteImport,
} as any)
const MinigamesRoute = MinigamesRouteImport.update({
  id: '/minigames',
  path: '/minigames',
  getParentRoute: () => rootRouteImport,
} as any)
const QuimicaRoute = QuimicaRouteImport.update({
  id: '/quimica',
  path: '/quimica',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circuito': typeof CircuitoRoute
  '/copiloto': typeof CopilotoRoute
  '/fotossintese': typeof FotossinteseRoute
  '/minigames': typeof MinigamesRoute
  '/quimica': typeof QuimicaRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circuito': typeof CircuitoRoute
  '/copiloto': typeof CopilotoRoute
  '/fotossintese': typeof FotossinteseRoute
  '/minigames': typeof MinigamesRoute
  '/quimica': typeof QuimicaRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circuito': typeof CircuitoRoute
  '/copiloto': typeof CopilotoRoute
  '/fotossintese': typeof FotossinteseRoute
  '/minigames': typeof MinigamesRoute
  '/quimica': typeof QuimicaRoute
  '/quiz': typeof QuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circuito'
    | '/copiloto'
    | '/fotossintese'
    | '/minigames'
    | '/quimica'
    | '/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circuito'
    | '/copiloto'
    | '/fotossintese'
    | '/minigames'
    | '/quimica'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/circuito'
    | '/copiloto'
    | '/fotossintese'
    | '/minigames'
    | '/quimica'
    | '/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircuitoRoute: typeof CircuitoRoute
  CopilotoRoute: typeof CopilotoRoute
  FotossinteseRoute: typeof FotossinteseRoute
  MinigamesRoute: typeof MinigamesRoute
  QuimicaRoute: typeof QuimicaRoute
  QuizRoute: typeof QuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuito': {
      id: '/circuito'
      path: '/circuito'
      fullPath: '/circuito'
      preLoaderRoute: typeof CircuitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copiloto': {
      id: '/copiloto'
      path: '/copiloto'
      fullPath: '/copiloto'
      preLoaderRoute: typeof CopilotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotossintese': {
      id: '/fotossintese'
      path: '/fotossintese'
      fullPath: '/fotossintese'
      preLoaderRoute: typeof FotossinteseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minigames': {
      id: '/minigames'
      path: '/minigames'
      fullPath: '/minigames'
      preLoaderRoute: typeof MinigamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quimica': {
      id: '/quimica'
      path: '/quimica'
      fullPath: '/quimica'
      preLoaderRoute: typeof QuimicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircuitoRoute: CircuitoRoute,
  CopilotoRoute: CopilotoRoute,
  FotossinteseRoute: FotossinteseRoute,
  MinigamesRoute: MinigamesRoute,
  QuimicaRoute: QuimicaRoute,
  QuizRoute: QuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
